### PR TITLE
Move rand and bincode test-only dependencies and document how to use …

### PR DESCRIPTION
**Pull request by dabreegster**
…FastGraph32 when embedded in a larger struct.

### CODE REVIEW

**Comment by easbar** [comment]
Cool, thanks a lot! Just a minor remark: Should we point out that FG32 is also useful when working (only) in a 64 bit environment to save some disk space? And mention the extra memory requirement?

We can also merge here and I'll update the readme in a following commit.

**Comment by dabreegster** [comment]
The README still has your note "Note that the resulting size on disk will be 50% less than when using `save_to_disk`, but 50% more RAM will be needed during the process of saving the graph to disk." -- do you think this also belongs on the rustdoc for serialize_with?

**Comment by easbar** [comment]
Yes or maybe it only belongs there? Creating the FG32 is what costs extra RAM, saving to disk does not (and is no longer part of the crate anyway)? In turn the size used on disk is smaller.

**Comment by dabreegster** [comment]
How's this?

**Comment by easbar** [comment]
Perfect, thanks!

**Pull request merged**
